language: cpp
dist: trusty
os: linux

include:
  - env: COMPILER=g++-6 BUILD=Debug STANDARD=17
    compiler: gcc
    addons:
      apt:
        update: true
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - boost1.67
          - doxygen
          - doxygen-doc
          - doxygen-latex
          - doxygen-gui
          - graphviz
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- mkdir doxygen
- doxygen Doxyfile
deploy:
  - provider: pages
    local_dir: $TRAVIS_BUILD_DIR/doxygen/html
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master

  - provider: script
    script:
    - curl -T bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ulismut:$BINTRAY_API_KEY "https://api.bintray.com/content/lismut/otus12/otus12/$TRAVIS_BUILD_NUMBER/bulk_server-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
